In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

In [2]:
file_path1 = '/content/drive/MyDrive/GTD_2018-2021.csv'

df1 = pd.read_csv(file_path1)

/tmp/ipython-input-1880624410.py:3: DtypeWarning: Columns (63,79,115) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(file_path1)

In [ ]:
df1.info

In [ ]:
gruppi_freq = df1['gname'].value_counts()

In [ ]:
gruppi_freq

gname
Unknown                                        10895
Taliban                                         5456
Islamic State of Iraq and the Levant (ISIL)     1802
Houthi extremists (Ansar Allah)                 1689
Al-Shabaab                                      1231
                                               ...
Taungthar Youth Guerrilla Force                    1
Arakan Liberation Party (ALP)                      1
Ahrar al-Sham                                      1
Zero Guerrilla Force                               1
Seven People Defense Force (SPDF)                  1
Name: count, Length: 536, dtype: int64

In [ ]:
gruppi_freq.head(481)

gname
Unknown                                        10895
Taliban                                         5456
Islamic State of Iraq and the Levant (ISIL)     1802
Houthi extremists (Ansar Allah)                 1689
Al-Shabaab                                      1231
                                               ...
M23                                                1
Jabal al-Islam Brigade                             1
Rajput extremists                                  1
S14                                                1
Sons of Zouari                                     1
Name: count, Length: 481, dtype: int64

In [ ]:
print(df1.columns.tolist())

['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended', 'resolution', 'country', 'country_txt', 'region', 'region_txt', 'provstate', 'city', 'latitude', 'longitude', 'specificity', 'vicinity', 'location', 'summary', 'crit1', 'crit2', 'crit3', 'doubtterr', 'alternative', 'alternative_txt', 'multiple', 'success', 'suicide', 'attacktype1', 'attacktype1_txt', 'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt', 'targtype1', 'targtype1_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targtype2', 'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3', 'natlty3_txt', 'gname', 'gsubname', 'gname2', 'gsubname2', 'gname3', 'gsubname3', 'motive', 'guncertain1', 'guncertain2', 'guncertain3', 'individual', 'nperps', 'nperpcap', 'claimed', 'claimmode', 'claimmode_txt', 'claim2', 'claimmode2', 'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim', 'weaptype1', 'weaptype1_txt', 'weapsubtype1', 'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4', 'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent', 'propextent_txt', 'propvalue', 'propcomment', 'ishostkid', 'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'divert', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome', 'hostkidoutcome_txt', 'nreleased', 'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related']

In [ ]:
# Stati più colpiti (conteggio eventi)
top_countries = df1['country_txt'].value_counts().reset_index()
top_countries.columns = ['country', 'num_attacks']

# Visualizza i primi 10
print(top_countries.head(10))

                            country  num_attacks
0                       Afghanistan         7640
1                              Iraq         3319
2                             India         2196
3                           Nigeria         2083
4                             Yemen         2057
5                       Philippines         1466
6                           Somalia         1293
7                          Pakistan         1287
8                             Syria          928
9  Democratic Republic of the Congo          865

In [ ]:
# Gruppi terroristici più attivi per paese
group_country = df1.groupby(['gname', 'country_txt']).size().reset_index(name='num_attacks')
# Escludi "Unknown" se vuoi solo i gruppi noti
group_country = group_country[group_country['gname'] != 'Unknown']
# Gruppi più attivi nel periodo
print(group_country.sort_values('num_attacks', ascending=False).head(10))

                                           gname  \
702                                      Taliban
316  Islamic State of Iraq and the Levant (ISIL)
289              Houthi extremists (Ansar Allah)
30                                    Al-Shabaab
186                                   Boko Haram
261                            Fulani extremists
546                      New People's Army (NPA)
437                                      Maoists
652                                  Separatists
38                Allied Democratic Forces (ADF)

                          country_txt  num_attacks
702                       Afghanistan         5455
316                              Iraq         1519
289                             Yemen         1418
30                            Somalia         1054
186                           Nigeria          806
261                           Nigeria          755
546                       Philippines          669
437                             India          535
652                          Cameroon          292
38   Democratic Republic of the Congo          285

In [ ]:
gruppi_religiosi = [
    "Abu Sayyaf Group (ASG)",
    "Adan-Abyan Province of the Islamic State",
    "Ahl al-Marouf",
    "Ahle Sunnat Wal Jamaat (ASWJ-Pakistan)",
    "Ahrar al-Sham",
    "Ahrar al-Sharqiya",
    "Al Bayda Province of the Islamic State",
    "Al-Aqsa Martyrs Brigade",
    "Al-Badr",
    "Al-Khobar",
    "Al-Qaida in the Arabian Peninsula (AQAP)",
    "Al-Qaida in the Indian Subcontinent",
    "Al-Qaida in the Islamic Maghreb (AQIM)",
    "Al-Shabaab",
    "Al-Umar Mujahideen",
    "Algeria Province of the Islamic State",
    "Allied Democratic Forces (ADF)",
    "Ansar Abi Bakr al-Siddiq Squadron",
    "Ansar Al-Khilafa (Philippines)",
    "Ansar Allah al-Awfiya",
    "Ansar Ghazwat-ul-Hind",
    "Ansar al-Furqan",
    "Ansar al-Islam (Burkina Faso)",
    "Ansar al-Sharia (Libya)",
    "Ansar al-Sunna (Mozambique)",
    "Ansar al-Tawhid",
    "Ansaru (Jama'atu Ansarul Muslimina Fi Biladis Sudan)",
    "Ansarullah Bangla Team",
    "Anti-Christian extremists",
    "Anti-Muslim extremists",
    "Anti-Semitic extremists",
    "Arakan Rohingya Salvation Army (ARSA)",
    "Asa'ib Ahl al-Haqq",
    "Ashab al-Kahf",
    "Bangsamoro Islamic Freedom Movement (BIFM)",
    "Barqa Province of the Islamic State",
    "Boko Haram",
    "Buddhist extremists",
    "Catholic extremists",
    "Caucasus Province of the Islamic State",
    "Central Africa Province of the Islamic State",
    "Christian extremists",
    "Derna Protection Force (DPF)",
    "East Asia Division of the Islamic State",
    "Fezzan Province of the Islamic State",
    "Free Alawite Movement",
    "Furqa 23",
    "Hafiz Gul Bahadur Group",
    "Hamas (Islamic Resistance Movement)",
    "Haqqani Network",
    "Hasam Movement",
    "Hay'at Tahrir al-Sham",
    "Hezbollah",
    "High Council of the Islamic Emirate",
    "Hind Province of the Islamic State",
    "Hindu extremists",
    "Hizb-ul-Ahrar (HuA)",
    "Hizbul Mujahideen (HM)",
    "Hurras al-Din",
    "Incite the Believers",
    "Iran-backed militia",
    "Islamic State in Bangladesh",
    "Islamic State in Egypt",
    "Islamic State in the Greater Sahara (ISGS)",
    "Islamic State of Iraq and the Levant (ISIL)",
    "Israeli extremists",
    "Jabal al-Islam Brigade",
    "Jabha East Africa",
    "Jaish al-Adl",
    "Jaish-e-Mohammad (JeM)",
    "Jama'atul Mujahideen Bangladesh (JMB)",
    "Jamaah Ansharut Daulah",
    "Jamaat Nusrat al-Islam wal Muslimin (JNIM)",
    "Jaysh al-Islam (Syria)",
    "Jewish Extremists",
    "Jihadi-inspired extremists",
    "Jund al-Khilafah (Tunisia)",
    "Kata'ib Hezbollah",
    "Khalistan Liberation Force",
    "Khalistani extremists",
    "Khorasan Chapter of the Islamic State",
    "Ku Klux Klan",
    "Lashkar-e-Islam (Pakistan)",
    "Lashkar-e-Jhangvi",
    "Lashkar-e-Mustafa (LeM)",
    "Lashkar-e-Taiba (LeT)",
    "Lions of Khilafah in the Maldives",
    "Lord's Resistance Army (LRA)",
    "Maute Group",
    "Mouhadine",
    "Moro Islamic Liberation Front (MILF)",
    "Mujahidin Indonesia Timur (MIT)",
    "Mullah Nazir Group",
    "Muslim Brotherhood",
    "Muslim extremists",
    "Najd Province of the Islamic State",
    "National Thowheeth Jama'ath",
    "Negara Islam Indonesia (NII)",
    "Okba Ibn Nafaa Brigade",
    "Omar Abdel Rahman Brigade",
    "Pakistan Province of the Islamic State",
    "Palestinian Islamic Jihad (PIJ)",
    "Popular Front of India (PFI)",
    "Pro-Palestinian extremists",
    "Qimant extremists",
    "Rab'Allah",
    "Rashtriya Swayamsevak Sangh",
    "Sabiqun Battalion",
    "Sadrist Movement",
    "Sanatan Sanstha",
    "Sarallah India Hezbollah",
    "Saraya al-Jihad Fi Bilad al-Sham",
    "Saraya al-Salam",
    "Shia Muslim extremists",
    "Shura Council of Benghazi Revolutionaries",
    "Shura Council of Mujahideen in Derna",
    "Sikh extremists",
    "Sinai Province of the Islamic State",
    "Sudanese Islamic Youth Movement",
    "Sumud Brigade",
    "Tajamo Ansar al-Islam",
    "Taliban",
    "Tehreek-e-Labbaik Pakistan (TLP)",
    "Tehrik al-Mojahedin",
    "Tehrik-i-Taliban Pakistan (TTP)",
    "The Owners of the White Flags",
    "The Resistance Front (TRF)",
    "Tripoli Province of the Islamic State",
    "Turkestan Islamic Party",
    "Vishwa Hindu Parishad (VHP)",
    "Wa'ed al-Tahrir",
    "White supremacists/nationalists",
    "Zaire Self-Defense Group",
    "uMkhonto we Sizwe Military Veterans Association (MKMVA)"
]

df_religiosi = df1[df1['gname'].isin(gruppi_religiosi)]

In [ ]:
df_attack_rel = df_religiosi[df_religiosi['doubtterr'] == 0]

In [ ]:

# Conta il numero di attacchi per paese
attacks_per_country = df_attack_rel['country_txt'].value_counts().reset_index()
attacks_per_country.columns = ['country', 'num_attacks']

In [ ]:
pip install pycountry

Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 45.9 MB/s eta 0:00:00
Installing collected packages: pycountry
Successfully installed pycountry-24.6.1

In [ ]:
import pycountry

def get_iso3(country_name):
    try:
        return pycountry.countries.lookup(country_name).alpha_3
    except:
        return None

attacks_per_country['iso_alpha'] = attacks_per_country['country'].apply(get_iso3)
# Filtra eventuali paesi senza codice ISO
attacks_per_country = attacks_per_country.dropna(subset=['iso_alpha'])

In [ ]:
import plotly.express as px

fig = px.choropleth(
    attacks_per_country,
    locations="iso_alpha",
    color="num_attacks",
    hover_name="country",
    color_continuous_scale="Reds",
    title="Heatmap degli attacchi terroristici per paese (2018-2021)"
)
fig.show()