In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive

In [ ]:
#caricamento file excel (lettura lenta -> conversione in csv)
file_path = '/content/drive/MyDrive/globalterrorismdb_0522dist.xlsx'


df = pd.read_excel(file_path)

In [ ]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaT,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaT,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaT,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaT,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaT,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [ ]:
#converisone csv
df.to_csv("df.csv", index=False)

In [ ]:
#verifica del dataset e della correttezza dei dati
file_path1 = '/content/drive/MyDrive/GTD.csv'

df1 = pd.read_csv(file_path1)

/tmp/ipython-input-327460695.py:4: DtypeWarning: Columns (4,31,33,54,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(file_path1)

In [ ]:
df_italy = df1[df1['country_txt'] == 'Italy']

In [ ]:

df_tuscany=df_italy[df_italy['provstate'] == 'Tuscany']
df_tuscany

Warning: Total number of columns (135) exceeds max_columns (20). Falling back to pandas display.

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
1709,197301170001,1973,1,17,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Tirrenia,43.627726,10.291712,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0.0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,4,Military,35.0,Military Transportation/Vehicle (excluding con...,NaN,"Cars, U.S. Military Personnel (4 cars)",217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,0.0,NaN,NaN,0.0,NaN,NaN,1,3.0,Minor (likely < $1 million),2000.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
2606,197410220002,1974,10,22,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.768732,11.256901,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0.0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,1,Business,3.0,Bank/Commerce,NaN,Bank of Florence,98.0,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Armed Proletarian Nuclei (NAP),NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,2.0,Automatic or Semi-Automatic Rifle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic firearm,2.0,NaN,NaN,NaN,NaN,NaN,1,3.0,Minor (likely < $1 million),15000.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
2661,197411160001,1974,11,16,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.768732,11.256901,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,FRG Consulate,75.0,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Baader-Meinhof Group,Holger Meins Commando,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,0.0,NaN,NaN,0.0,NaN,NaN,1,3.0,Minor (likely < $1 million),5000.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,1,0,1,1,NaN
3720,197604140002,1976,4,14,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.768732,11.256901,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,1,Business,1.0,Gas/Oil/Electric,NaN,Texaco Oil Offices,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Armed Communist Formations,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,0.0,NaN,NaN,0.0,NaN,NaN,1,4.0,Unknown,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
3727,197604170001,1976,4,17,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.768732,11.256901,1.0,0,NaN,NaN,1,1,1,0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,Spanish consulate,185.0,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Armed Communist Formations,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,19.0,Molotov Cocktail/Petrol Bomb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Molotov cocktails,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133290,201406100083,2014,6,10,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.771033,11.248001,1.0,0,NaN,06/10/2014: An explosive device detonated insi...,1,1,1,0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,14,Private Citizens & Property,84.0,Political Party Member/Rally,Democratic Party (PD),Offices,98.0,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anarchists,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0,-99.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,17.0,Other Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A homemade device made of three camping gas ca...,0.0,0.0,0.0,0.0,0.0,0.0,1,3.0,Minor (likely < $1 million),-99.0,An office was damaged in this attack.,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Bomb set off at offices of Renzi's PD in Flor...","""Homemade Bomb Explodes Outside PD Offices In ...",NaN,START Primary Collection,-9,-9,0,-9,NaN
141922,201412210068,2014,12,21,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.769550,11.258484,1.0,0,NaN,12/21/2014: Assailants set fire to railway tra...,1,1,1,0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,19,Transportation,100.0,Train/Train Tracks/Trolley,Unknown,Railway Tracks,98.0,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anarchists,NaN,NaN,NaN,NaN,NaN,"The specific motive is unknown; however, sourc...",0.0,NaN,NaN,0,-99.0,0.0,1.0,7.0,"Posted to website, blog, etc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,20.0,Gasoline or Alcohol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Two vessels filled with incendiary liquid were...,0.0,0.0,0.0,0.0,0.0,0.0,1,4.0,Unknown,-99.0,Railway tracks were damaged in this attack.,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Investigators probing train sabotage 'working...","""Sabotage disrupts rail services, No-TAV blame...","""Italy trains delayed after 'arson attack' alo...",START Primary Collection,-9,-9,0,-9,NaN
171520,201701010006,2017,1,1,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Florence,43.769560,11.255814,1.0,0,NaN,01/01/2017: An explosive device detonated as i...,1,1,1,0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,1,Business,7.0,Retail/Grocery/Bakery,Unknown,Bookstore,98.0,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anarchists,NaN,NaN,NaN,NaN,NaN,"The specific motive is unknown; however, sourc...",0.0,NaN,NaN,0,5.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,9.0,Letter Bomb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A parcel bomb with a timer was used in the att...,0.0,0.0,0.0,1.0,0.0,0.0,1,3.0,Minor (likely < $1 million),-99.0,A shop was damaged in this attack.,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Rome - 5 anarchists held in Italy over Jan 1 ...","""Parcel bomb at far-right bookshop wounds Ital...","""Rome - Italian policeman injured in far-right...",START Primary Collection,-9,-9,0,-9,NaN
188914,201808020044,2018,8,2,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Pistoia,43.930136,10.908116,1.0,0,NaN,08/02/2018: Two assailants opened fire on a Ga...,1,1,1,0,NaN,NaN,0.0,0,0,2,Armed Assault,NaN,NaN,NaN,NaN,14,Private Citizens & Property,71.0,Race/Ethnicity Identified,Not Applicable,Migrant,73.0,Gambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,Two unaffiliated individuals claimed responsib...,0.0,NaN,NaN,1,-99.0,0.0,1.0,8.0,Personal claim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,5.0,Unknown Gun Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The assailants claimed the incident was a prank.,"""Minors behind migrant shooting incident,"" Ans...","""Migrant shot at in Pistoia,"" Ansa.it, August ...",NaN,START Primary Collection,-9,-9,1,1,NaN
197893,201907220009,2019,7,22,NaN,0,NaN,98,Italy,8,Western Europe,Tuscany,Rovezzano,43.765066,11.312941,1.0,0,NaN,07/22/2019: Assailants set fire to a rail tran...,1,1,1,0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,19,Transportation,100.0,Train/Train Tracks/Trolley,Rete Ferroviaria Italiana (RFI),Rail Transformer Room,98.0,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anarchists,NaN,NaN,NaN,NaN,NaN,"The specific motive is unknown; however, sourc...",0.0,NaN,NaN,0,-99.0,0.0,1.0,7.0,"Posted to website, blog, etc.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,18.0,Arson/Fire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1,3.0,Minor (likely < $1 million),-99.0,A rail transformer room was damaged in this at...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""Train chaos: if anarchists, attack on State -...","""Train chaos after suspected anarchist,"" Ansa....","""Italy hit by 4-hour train delays after suspec...",START Primary Collection,-9,-9,0,-9,NaN

Warning: Total number of columns (135) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df1.head(26)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
5,197001010002,1970,1,1,NaN,0,NaN,217,United States,1,...,"The Cairo Chief of Police, William Petersen, r...","""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,-9,-9,0,-9,NaN
6,197001020001,1970,1,2,NaN,0,NaN,218,Uruguay,3,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
7,197001020002,1970,1,2,NaN,0,NaN,217,United States,1,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
8,197001020003,1970,1,2,NaN,0,NaN,217,United States,1,...,The New Years Gang issue a communiqué to a loc...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",Hewitt Project,0,0,0,0,NaN
9,197001030001,1970,1,3,NaN,0,NaN,217,United States,1,...,"Karl Armstrong's girlfriend, Lynn Schultz, dro...",Committee on Government Operations United Stat...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...",Hewitt Project,0,0,0,0,NaN
10,197001050001,1970,1,1,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
11,197001060001,1970,1,6,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
12,197001080001,1970,1,8,NaN,0,NaN,98,Italy,8,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,1,1,NaN
13,197001090001,1970,1,9,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
14,197001090002,1970,1,9,NaN,0,NaN,217,United States,1,...,The fire began at 8:30 PM. The Armed Commandos...,Committee on the Judiciary United States Sena...,"""No Evidence Of Arson Found In Barkers Fire,"" ...","""Toward People's War for Independence and Soci...",Hewitt Project,0,0,0,0,NaN
15,197001100001,1970,1,10,NaN,0,NaN,499,East Germany (GDR),9,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
16,197001110001,1970,1,11,NaN,0,NaN,65,Ethiopia,11,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
17,197001120001,1970,1,12,NaN,0,NaN,217,United States,1,...,"One half hour after the bomb explosion, an ano...","""Blast Damages Flatbush School,"" New York Time...","Linda Greenhouse, ""Madison School Puzzled By B...",Committee on Government Operations United Stat...,Hewitt Project,-9,-9,0,-9,NaN
18,197001120002,1970,1,12,NaN,0,NaN,217,United States,1,...,NaN,Committee on the Judiciary United States Sena...,"""Toward People's War for Independence and Soci...",NaN,Hewitt Project,-9,-9,0,-9,NaN
19,197001130001,1970,1,13,NaN,0,NaN,217,United States,1,...,The store was a White owned business operating...,Committee on Government Operations United Stat...,NaN,NaN,Hewitt Project,-9,-9,0,-9,NaN
20,197001140001,1970,1,14,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Peter F. Nardulli and Jeffrey M. Stonecash, ""P...",Hewitt Project,-9,-9,0,-9,NaN
21,197001150001,1970,1,15,NaN,0,NaN,218,Uruguay,3,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
22,197001190002,1970,1,19,NaN,0,NaN,217,United States,1,...,Witnesses observed three African American male...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Seattle University, ""1965-1975: Troubled Times...",Hewitt Project,-9,-9,0,-9,NaN
23,197001190003,1970,1,19,NaN,0,NaN,217,United States,1,...,Judith and Silas Bissell were both members of ...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Earl Caldwell, ""Fear Grows In Seattle As Polic...",Hewitt Project,-9,-9,0,-9,NaN
24,197001190004,1970,1,19,"January 19-20, 1970",0,NaN,217,United States,1,...,The building might have been shot at a second ...,Committee on Government Operations United Stat...,"""Black Panthers Say Office Was Bombed,"" New Yo...","""30 Shots Fired Into Office of Panthers in Jer...",Hewitt Project,-9,-9,0,-9,NaN
25,197001200001,1970,1,20,NaN,0,NaN,83,Guatemala,2,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [ ]:
#filtro per anno dal 2017 in poi
df_2018_2020 = df1[df1['iyear'] > 2017]

In [ ]:
df_2018_2020.to_csv("GTD_2018-2020.csv", index=False)

In [ ]:
#-------------------------

In [ ]:
#stesso processo per i dati del 2021

file_path2 = '/content/drive/MyDrive/globalterrorismdb_2021Jan-June_1222dist.xlsx'


df2 = pd.read_excel(file_path2)


df2.to_csv("GTD2.csv", index=False)

In [ ]:
#-------------------------

In [ ]:
#join  tra i dati del 2018-2020 + 2021

# Carica il primo dataset (filtrato con anno > 2017)
df_1= pd.read_csv("/content/drive/MyDrive/GTD_2018-2020.csv", low_memory=False)

# Carica il secondo dataset
df_2 = pd.read_csv("/content/drive/MyDrive/GTD_2021.csv", low_memory=False)

# Unisci i due dataset (uno sotto l'altro)
df_unito = pd.concat([df_1, df_2], ignore_index=True)

# Mostra qualche riga per verifica
print(df_unito.head())

# Salva il dataset unito
df_unito.to_csv("GTD_2018-2021.csv", index=False)

        eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  201801010001   2018       1     1        NaN         0        NaN       95
1  201801010003   2018       1     1        NaN         0        NaN       95
2  201801010004   2018       1     1        NaN         0        NaN      153
3  201801010005   2018       1     1        NaN         0        NaN      153
4  201801010032   2018       1     1        NaN         0        NaN      147

  country_txt  region  ...                                           addnotes  \
0        Iraq      10  ...                                                NaN
1        Iraq      10  ...                                                NaN
2    Pakistan       6  ...                                                NaN
3    Pakistan       6  ...                                                NaN
4     Nigeria      11  ...  Casualty numbers conflict across sources. Foll...

                                              scite1  \
0  "Iraq: Security Roundup 1900 GMT 1 January 201...
1  "Iraq: Roundup of Violent Activities Targeting...
2  "Eight people, including three security offici...
3  "Eight people, including three security offici...
4  "Three killed in Adamawa bomb attack," Nigeria...

                                              scite2  \
0                                                NaN
1                                                NaN
2  "Balochistan blasts: 8 people including 3 secu...
3  "Balochistan blasts: 8 people including 3 secu...
4  "New Year's Day blast kills at least 3 in Nige...

                                              scite3  \
0                                                NaN
1                                                NaN
2  "Twin blasts hit Balochistan; 8 injured," Yaho...
3  "Twin blasts hit Balochistan; 8 injured," Yaho...
4  "Boko Haram bomb kills 3 in Adamawa," Latest N...

                   dbsource  INT_LOG  INT_IDEO INT_MISC INT_ANY  \
0  START Primary Collection        0         1        0       1
1  START Primary Collection       -9        -9        0      -9
2  START Primary Collection       -9        -9        0      -9
3  START Primary Collection       -9        -9        0      -9
4  START Primary Collection        0         0        0       0

                      related
0                         NaN
1                         NaN
2  201801010004, 201801010005
3  201801010004, 201801010005
4                         NaN

[5 rows x 135 columns]

In [ ]:
df_full= pd.read_csv("/content/GTD_2018-2021.csv")

/tmp/ipython-input-541798261.py:1: DtypeWarning: Columns (63,79,115) have mixed types. Specify dtype option on import or set low_memory=False.
  df_full= pd.read_csv("/content/GTD_2018-2021.csv")

In [ ]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788 entries, 0 to 31787
Columns: 135 entries, eventid to related
dtypes: float64(56), int64(23), object(56)
memory usage: 32.7+ MB

In [ ]:
df_1.shape + df_2.shape

(26828, 135, 4960, 135)

In [ ]:
df_full.shape

(31788, 135)